console.log(+'15' + true);
console.log(+'15' + 3);
console.log(3 + true);
console.log(+'15' * true);
console.log(+'15' * 3);
console.log(3 * true);
console.log(+'15' / true);
console.log(+'15' / 3);
console.log(3 / true);
console.log(Number('123'));
console.log(String( 123));
console.log(Boolean(0));